# Generated by Django 3.2.5 on 2021-10-04 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='linked',
            new_name='liked',
        ),
    ]
